version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: php_mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - php_mysql_network
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10

  php_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_mysql_app
    restart: unless-stopped
    environment:
      DB_HOST: mysql
    ports:
      - '3000:3000'
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/var/www/html
    networks:
      - php_mysql_network

volumes:
  mysql_data:

networks:
  php_mysql_network:
    driver: bridge
